name: Unit Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./
      run: npm install
    - name: Run tests
      working-directory: ./
      run: npm run test